export default{
    changeUserMsg(state,payload)
    {
        state.userMsg=payload.userMsg;
    },
    //回复错误信息
    changeResponse(state,payload)
    {
        state.response=payload.response
    },
    //登录状态
    changeLoginType(state,payload)
    {
        state.loginType=payload.loginType;
    },
    //用户详情
    changeUserDetail(state,payload)
    {
        state.userDetail=payload.userDetail;
    },
    //最新页所有动态
    changeAllMoments(state,payload)
    {
        state.allMoments=payload.allMoments
    },
    //
    /*changeHotMoment(state,payload)
    {
        state.hotMoment=payload.hotMoment
    }*/
    //动态详情
    changeMomentDetail(state,payload)
    {
        state.momentDetail=payload.momentDetail
    },
    //搜索
    changeSearchResult(state,payload)
    {
        state.searchResult=payload.searchResult;
    },
    //评论更新的动态详情
    changeMomentDetails(state,payload)
    {
        state.momentDetails=payload.momentDetails;
    },
    //获取信息
    changeChatMsg(state,payload){
        state.chatMsg=payload.chatMsg;
    },
}